### ISSUE TITLE
Extract table issue - stream algo, no guessed area

### ISSUE THREAD

**Issue by orchardc** [BobLd/tabula-sharp#13]
Hi @BobLd 

First of all, thanks so much for sharing this useful library!!

I used the BasicExtractionAlgorithm try to extract tables from a PDF file, a sample attached.
[test3.pdf](https://github.com/BobLd/tabula-sharp/files/5258457/test3.pdf)

The second-page output is just fine, as I expected:
![image](https://user-images.githubusercontent.com/16193516/93828118-9d0b9d00-fc62-11ea-95b4-162b100dd97a.png)

but for the first page, because there are some text on the top of the table, the column output is wrong (see highlight in yellow).
![image](https://user-images.githubusercontent.com/16193516/93828076-8bc29080-fc62-11ea-94ce-f0f8a0b3b454.png)

What's your view to fix it please? Maybe there is a way (for the first page, ignore those non-table text??)

**Comment by BobLd** [comment]
Hi @orchardc,

Thanks for raising the issue.

I did a quick test comparing the output difference with [`tabula-py`](https://github.com/chezou/tabula-py) (`stream=True` means that `BasicExtractionAlgorithm` is used), and here are the results:

- Obtaining the same results as yours:
```python
dfs = tabula.read_pdf(pdf_path, stream=True, guess=False, pages=1)
```
![image](https://user-images.githubusercontent.com/38405645/93829443-903c7880-fc65-11ea-9993-b8803f1c0355.png)

- Obtaining the _correct_ results:
```python
dfs = tabula.read_pdf(pdf_path, stream=True, guess=True, pages=1)
```
![image](https://user-images.githubusercontent.com/38405645/93829503-a9ddc000-fc65-11ea-8713-dd1fb63a198b.png)

Drawing a quick concusion from these tests, I would say that the issue is that no `guess` is done regarding the area where the table is located. 

I think this is linked to the [`NurminenDetectionAlgorithm`](https://github.com/BobLd/tabula-sharp/blob/master/Tabula/Detectors/NurminenDetectionAlgorithm.cs) class not being implemented for the moment. The problem is that this class is doing some image processing (the pdf page is converted to an image and then processed), and this cannot be done easily in dotnet core.

I will try to find a solution to that, either by passing the image processing or finding a way to do the processing.

If you find a way to find the candidate table area, you could use `PageArea.GetArea(PdfRectangle area)` to narrow down the region, and extract only on this region.

**Comment by orchardc** [comment]
Hi @BobLd , thanks for your quick response and try to find a solution.
Could you give me a tip how to use PageArea.GetArea(PdfRectangle area) base on my pdf sample??
I'm not sure how to tell the code to narrow down the region.

Currently I use the following code to get tables
```
                    ObjectExtractor oe = new ObjectExtractor(document);
                    PageArea page = oe.Extract(2);
                    IExtractionAlgorithm ea = new BasicExtractionAlgorithm();
                    List<Table> tables = ea.Extract(page);

```

**Comment by BobLd** [comment]
You can use the code below to narrow down thee area (knowing which area is a manual process for the moment):
```csharp
IExtractionAlgorithm ea = new BasicExtractionAlgorithm();
var newArea = page.GetArea(new PdfRectangle(50.0, 80, 800, 420));
List<Table> tables = ea.Extract(newArea);
```
gives you the correct results:
![image](https://user-images.githubusercontent.com/38405645/93865258-fc4acb00-fcbd-11ea-8fa9-d4c8cba43c86.png)

When `NurminenDetectionAlgorithm` will be implemented, it will guess by itself which area to analyse.

**Comment by BobLd** [comment]
Hi @orchardc ,

I have implemented the `SimpleNurminenDetectionAlgorithm` class that will help you find table regions in a page. It is available in the new release [here](https://github.com/BobLd/tabula-sharp/releases). 

You can use it like this:
```csharp
SimpleNurminenDetectionAlgorithm detector = new SimpleNurminenDetectionAlgorithm();
var regions = detector.Detect(page);

foreach (var region in regions)
{
    IExtractionAlgorithm ea = new BasicExtractionAlgorithm();
    var newArea = page.GetArea(region.BoundingBox);
    List<Table> tables = ea.Extract(newArea);
    [...]
```

You should get the correct result in the case of your pdf example.

**Comment by orchardc** [comment]
@BobLd This is amazing, thank you for your great work!!

**Comment by emrebiber** [comment]
Hi @BobLd ,

Thanks for such an awesome library. In my pdf file, for some reason, two columns are merged (I attached a couple of images) when I'm trying to extract the table. I was wondering maybe you can help me to determine what might cause that issue. I can also send the pdf file via email since it has sensitive information. Thanks in advance.

![pdf](https://user-images.githubusercontent.com/10804043/105953642-c9518300-6073-11eb-8aec-6199630636d9.PNG)
![dotnet](https://user-images.githubusercontent.com/10804043/105953639-c8b8ec80-6073-11eb-9c63-4cc30222c4b5.PNG)

**Comment by BobLd** [comment]
Hi @emrebiber, would you mind creating a new issue? I'll answer there.
