### ISSUE TITLE
Merged columns when extracting tables

### ISSUE THREAD

**Issue by emrebiber** [BobLd/tabula-sharp#16]
Hi @BobLd ,

Thanks for such an awesome library. In my pdf file, for some reason, two columns are merged (I attached a couple of images) when I'm trying to extract the table. I was wondering maybe you can help me to determine what might cause that issue. I can also send the pdf file via email since it has sensitive information. Thanks in advance.

![pdf](https://user-images.githubusercontent.com/10804043/105953642-c9518300-6073-11eb-8aec-6199630636d9.PNG)
![dotnet](https://user-images.githubusercontent.com/10804043/105953639-c8b8ec80-6073-11eb-9c63-4cc30222c4b5.PNG)

_Originally posted by @emrebiber in https://github.com/BobLd/tabula-sharp/issues/13#issuecomment-768074036_

**Comment by BobLd** [comment]
Hi @emrebiber, thanks for raising an issue.

I think the issue could come from two sources:
- PdfPig 
   - Could you check that the letters/words bounding boxes are correctly computed by running [DLAViewer](https://github.com/BobLd/DocumentLayoutAnalysis/tree/master/DocumentLayoutAnalysis/DlaViewer) with your document? If they are not correctly displayed (for example the bounding boxes don't have height), this might create issues.
- tabula-sharp
   - Could you put the code you've used to extract the table (which algo did you used)?
   - If your document contains non-public information, keep if for yourself. But you could try to recreate the issue with another docment and put it here.

**Possible quick win**: Can you try using [camelot-sharp](https://github.com/BobLd/camelot-sharp) instead of tabula-sharp? This library's goal is the same but works differently. The nuget package is available, but only as a pre-release.

**Comment by emrebiber** [comment]
Hi again,

- DLAViewer
I did run it and attached xml also here I hope this will help.
[Test.txt](https://github.com/BobLd/tabula-sharp/files/5900716/Test.txt)

- tabula-sharp

I did use SimpleNurminenDetectionAlgorithm and BasicExtractionAlgorithm. 
Here is the code snippet:

```
using (var document = PdfDocument.Open(model.File.InputStream, new ParsingOptions() { ClipPaths = true }))
{
      ObjectExtractor oe = new ObjectExtractor(document);
      PageArea pageArea = oe.Extract(i);
      var detector = new SimpleNurminenDetectionAlgorithm();
      var regions = detector.Detect(pageArea);
      IExtractionAlgorithm ea = new BasicExtractionAlgorithm();
      var tables = ea.Extract(pageArea.GetArea(regions[0].BoundingBox));
      var table = tables[0];
      var rows = table.Rows;
}
```
I also attached the pdf file that I'm trying.
[Test.pdf](https://github.com/BobLd/tabula-sharp/files/5900692/Test.pdf)

I can for sure try camelot-sharp but do you have some kind of instructions on how can I try it?

**Comment by BobLd** [comment]
Looking at the pdf, my first guess would be that the 2 columns are merged together because of this word spanning 2 columns:
![image](https://user-images.githubusercontent.com/38405645/106430352-963c3480-6463-11eb-895d-6757200b2b03.png)
It is going to be difficult for the algo to know how to split that. In which column would you put this word?

Concerning Camelot, I took that from my tests:
```csharp
Lattice lattice = new Lattice(new OpenCvImageProcesser(), new BasicSystemDrawingProcessor());
// In your case, it is better to use the Stream BaseParser (rather than the Lattice parser)
var tables = lattice.ExtractTables(doc.GetPage(1), layout_kwargs: null);
```

**Comment by emrebiber** [comment]
You are right that's the word merging those columns together. Thanks for your help. This library is so useful.
